// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class FileContent
    {
        public int Id { get; set; }
        public int TlogId { get; set; }
        public string FileContent1 { get; set; }
        public DateTime Timestamp { get; set; }

        public virtual TransactionLog Tlog { get; set; }
    }
}