// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class Location
    {
        public Location()
        {
            RoutePerformance = new HashSet<RoutePerformance>();
            RouteStop = new HashSet<RouteStop>();
        }

        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public string CustCustParentId { get; set; }
        public string CustCustChildId { get; set; }
        public string CustLocationId { get; set; }
        public string CustMiscQualifierId { get; set; }
        public int? CourierId { get; set; }
        public string CourierLocationId { get; set; }
        public string ContractStopId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Plus4 { get; set; }
        public bool Active { get; set; }
        public string TicketNo { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }
        public decimal? Lat { get; set; }
        public decimal? Lon { get; set; }
        public string MapUrl { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<RoutePerformance> RoutePerformance { get; set; }
        public virtual ICollection<RouteStop> RouteStop { get; set; }
    }
}