// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class Log
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public DateTime TimeStamp { get; set; }
    }
}