// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class MessageLog
    {
        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public int? CourierId { get; set; }
        public string CcpmsgId { get; set; }
        public string CustReference { get; set; }
        public string CourierReference { get; set; }
        public string Status { get; set; }
        public bool? Processed { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
    }
}