// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class OrderParcel
    {
        public OrderParcel()
        {
            Exception = new HashSet<Exception>();
            InverseParent = new HashSet<OrderParcel>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int? ParcelTypeId { get; set; }
        public int OrderId { get; set; }
        public string Barcode { get; set; }
        public string ExtParcelId { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public int? Weight { get; set; }
        public string Comment { get; set; }
        public string CustomerReference1 { get; set; }
        public string CustomerReference2 { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }
        public string CcpmsgId { get; set; }

        public virtual Order Order { get; set; }
        public virtual ParcelType ParcelType { get; set; }
        public virtual OrderParcel Parent { get; set; }
        public virtual ICollection<Exception> Exception { get; set; }
        public virtual ICollection<OrderParcel> InverseParent { get; set; }
    }
}