// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class Order
    {
        public Order()
        {
            Exception = new HashSet<Exception>();
            OrderParcel = new HashSet<OrderParcel>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int CourierId { get; set; }
        public int? DriverId { get; set; }
        public int? FleetId { get; set; }
        public int? ServiceTypeId { get; set; }
        public int? ServiceLevelId { get; set; }
        public DateTime OrderDate { get; set; }
        public string PlacedBy { get; set; }
        public DateTime? PickupFrom { get; set; }
        public DateTime? PickupTo { get; set; }
        public DateTime? DeliveryFrom { get; set; }
        public DateTime? DeliveryTo { get; set; }
        public string CustomerReference1 { get; set; }
        public string CustomerReference2 { get; set; }
        public string OriginPhone { get; set; }
        public string OriginName { get; set; }
        public string OriginAddress1 { get; set; }
        public string OriginAddress2 { get; set; }
        public string OriginCity { get; set; }
        public string OriginState { get; set; }
        public string OriginZip { get; set; }
        public string OriginPlus4 { get; set; }
        public string OriginCountry { get; set; }
        public string OriginRemarks { get; set; }
        public string DestinationPhone { get; set; }
        public string DestinationName { get; set; }
        public string DestinationAddress1 { get; set; }
        public string DestinationAddress2 { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationState { get; set; }
        public string DestinationZip { get; set; }
        public string DestinationPlus4 { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationRemarks { get; set; }
        public string OrderStatus { get; set; }
        public string Podtext { get; set; }
        public string Podsignature { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }
        public string CcpmsgId { get; set; }
        public DateTime? TimeDelivered { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Fleet Fleet { get; set; }
        public virtual ServiceLevel ServiceLevel { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<Exception> Exception { get; set; }
        public virtual ICollection<OrderParcel> OrderParcel { get; set; }
    }
}