// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class ParcelType
    {
        public ParcelType()
        {
            OrderParcel = new HashSet<OrderParcel>();
            RouteStopParcel = new HashSet<RouteStopParcel>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int CourierId { get; set; }
        public string Description { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public int? Weight { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderParcel> OrderParcel { get; set; }
        public virtual ICollection<RouteStopParcel> RouteStopParcel { get; set; }
    }
}