// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class RouteStopParcel
    {
        public RouteStopParcel()
        {
            Exception = new HashSet<Exception>();
            InverseParent = new HashSet<RouteStopParcel>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int? ParcelTypeId { get; set; }
        public int RouteStopId { get; set; }
        public string Barcode { get; set; }
        public string ExtParcelId { get; set; }
        public DateTime? ScannedIn { get; set; }
        public string ScannedInBy { get; set; }
        public DateTime? ScannedOut { get; set; }
        public string ScannedOutBy { get; set; }
        public string ScannedInDepotId { get; set; }
        public string ScannedOutDepotId { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public int? Weight { get; set; }
        public string Comment { get; set; }
        public string Reference { get; set; }
        public string CustomerReference1 { get; set; }
        public string CustomerReference2 { get; set; }
        public string CcpmsgId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }

        public virtual ParcelType ParcelType { get; set; }
        public virtual RouteStopParcel Parent { get; set; }
        public virtual RouteStop RouteStop { get; set; }
        public virtual ICollection<Exception> Exception { get; set; }
        public virtual ICollection<RouteStopParcel> InverseParent { get; set; }
    }
}