// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class Route
    {
        public Route()
        {
            RoutePerformance = new HashSet<RoutePerformance>();
            RouteStop = new HashSet<RouteStop>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int CourierId { get; set; }
        public int? FleetId { get; set; }
        public int? DefaultDriverId { get; set; }
        public string RouteIdext { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string Comments { get; set; }
        public string CcpmsgId { get; set; }
        public string TicketNo { get; set; }
        public string RouteIdextQual1 { get; set; }
        public string RouteIdextQual2 { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }
        public int? DriverIdext { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver DefaultDriver { get; set; }
        public virtual Fleet Fleet { get; set; }
        public virtual ICollection<RoutePerformance> RoutePerformance { get; set; }
        public virtual ICollection<RouteStop> RouteStop { get; set; }
    }
}