// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class RouteStop
    {
        public RouteStop()
        {
            RouteStopParcel = new HashSet<RouteStopParcel>();
        }

        public int Id { get; set; }
        public int RouteStopTypeId { get; set; }
        public int RouteId { get; set; }
        public int LocationId { get; set; }
        public int? DriverId { get; set; }
        public DateTime PostDate { get; set; }
        public int Sequence { get; set; }
        public DateTime? TimeMin { get; set; }
        public DateTime? TimePreferred { get; set; }
        public DateTime? TimeMax { get; set; }
        public DateTime? TimeArrived { get; set; }
        public DateTime? TimeCompleted { get; set; }
        public string Status { get; set; }
        public string Podtext { get; set; }
        public string Podsignature { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
        public string CcpmsgId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedWhen { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedWhen { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public int? ContractId { get; set; }
        public string Cbflag { get; set; }
        public string CompletionType { get; set; }
        public bool? Active { get; set; }
        public string UserField0 { get; set; }
        public string UserField1 { get; set; }
        public string UserField2 { get; set; }
        public string UserField3 { get; set; }
        public string UserField4 { get; set; }
        public string UserField5 { get; set; }
        public string UserField6 { get; set; }
        public string UserField7 { get; set; }
        public string UserField8 { get; set; }
        public string UserField9 { get; set; }
        public DateTime? LoadedToDw { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Location Location { get; set; }
        public virtual Route Route { get; set; }
        public virtual RouteStopType RouteStopType { get; set; }
        public virtual ICollection<RouteStopParcel> RouteStopParcel { get; set; }
    }
}