// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class SupportTicket
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Topic { get; set; }
        public string Priority { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public DateTime TimeStamp { get; set; }

        public virtual InternetUser User { get; set; }
    }
}