// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FGPortal.Models
{
    public partial class TransactionLog
    {
        public TransactionLog()
        {
            FileContent = new HashSet<FileContent>();
        }

        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public int? CourierId { get; set; }
        public string CcpfileId { get; set; }
        public string Direction { get; set; }
        public string File { get; set; }
        public string Port { get; set; }
        public string Status { get; set; }
        public bool? Processed { get; set; }
        public DateTime? Timestamp { get; set; }

        public virtual Courier Courier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<FileContent> FileContent { get; set; }
    }
}